### ISSUE TITLE
Add PR templates to all repos

### ISSUE THREAD

**Issue by wonhyeongseo** [42Gyeongsan-side-project/reference#2]
- [x] Server https://github.com/42Gyeongsan-side-project/server/pull/11
- [x] iOS https://github.com/42Gyeongsan-side-project/iOS/pull/7
- [x] Frontend https://github.com/42Gyeongsan-side-project/frontend/pull/5

**Comment by joejaeyoung** [comment]
이슈는 리뷰 더 빨리 받을 수 있다고 PR 템플릿에 나와서 오타 같습니다.
